# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# A sample workflow which sets up Snyk to analyze the full Snyk platform (Snyk Open Source, Snyk Code,
# Snyk Container and Snyk Infrastructure as Code)
# The setup installs the Snyk CLI - for more details on the possible commands
# check https://docs.snyk.io/snyk-cli/cli-reference
# The results of Snyk Code are then uploaded to GitHub Security Code Scanning
#
# In order to use the Snyk Action you will need to have a Snyk API token.
# More details in https://github.com/snyk/actions#getting-your-snyk-token
# or you can signup for free at https://snyk.io/login
#
# For more examples, including how to limit scans to only high-severity issues
# and fail PR checks, see https://github.com/snyk/actions/


         
       
name: Snyk Security Scan

on:
  push:
    branches: ["Security_branch"]
  pull_request:
    branches: ["Security_branch"]

permissions:
  contents: read

jobs:
  snyk-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install Snyk CLI
        run: npm install -g snyk
      
      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
      
      # Scan HTML files
      - name: Run Snyk on HTML files
        run: snyk test --all-projects
        continue-on-error: true
      
      # Scan Java files specifically
      - name: Run Snyk on Java files
        run: |
          if [ -f pom.xml ]; then
            snyk test --file=pom.xml
          elif [ -f build.gradle ]; then
            snyk test --file=build.gradle
          else
            echo "No standard Java build file found, scanning Java files directly"
            find . -name "*.java" | xargs snyk test --skip-unresolved
          fi
        continue-on-error: true
      
      # Generate and upload security report
      - name: Generate Snyk report
        run: snyk monitor --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
     
