name: Snyk Security Scan
on:
  push:
    branches: ["Security_branch"]
  pull_request:
    branches: ["Security_branch"]
permissions:
  contents: read
  security-events: write  # Required for uploading SARIF results
jobs:
  snyk-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install Snyk CLI
        run: npm install -g snyk
      
      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
      
      # List all files to help with debugging
      - name: List files in repository
        run: find . -type f | grep -v ".git" | sort
      
      # Scan using Snyk's Code security scanning and output SARIF for GitHub
      - name: Run Snyk Code scan
        run: snyk code test --sarif > snyk-code.sarif
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
      # Upload Snyk Code results to GitHub Security
      - name: Upload Snyk Code SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif
          category: snyk-code
      
      # Monitor using Snyk Code
      - name: Monitor with Snyk Code
        run: snyk code monitor
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
      # Scan Java files and generate SARIF
      - name: Scan Java files (if any)
        run: |
          java_files=$(find . -name "*.java" -type f)
          if [ -n "$java_files" ]; then
            echo "Found Java files, scanning for vulnerabilities"
            snyk test --scan-all-unmanaged --sarif > snyk-java.sarif
          else
            echo "No Java files found"
            echo '{"runs":[]}' > snyk-java.sarif
          fi
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
      # Upload Java scan results to GitHub Security
      - name: Upload Java scan SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-java.sarif
          category: snyk-java
      
      # Scan HTML files and generate SARIF
      - name: Scan HTML files (if any)
        run: |
          html_files=$(find . -name "*.html" -type f)
          if [ -n "$html_files" ]; then
            echo "Found HTML files, scanning for vulnerabilities"
            snyk test --scan-all-unmanaged --sarif > snyk-html.sarif
          else
            echo "No HTML files found"
            echo '{"runs":[]}' > snyk-html.sarif
          fi
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
      # Upload HTML scan results to GitHub Security
      - name: Upload HTML scan SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-html.sarif
          category: snyk-html
