name: Snyk Security Scan Excel

on:
  push:
    branches: [ Security_branch ]
  pull_request:
    branches: [ Security_branch ]
  

jobs:
  snyk_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Snyk CLI
        uses: snyk/actions/setup@master
      
      - name: Snyk auth
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
      
      - name: Snyk test
        run: snyk test --all-projects --org=${{ secrets.SNYK_ORG_ID }}
        continue-on-error: true
      
      - name: Snyk monitor
        run: snyk monitor --all-projects --org=${{ secrets.SNYK_ORG_ID }}
        continue-on-error: true
