# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# A sample workflow which sets up Snyk to analyze the full Snyk platform (Snyk Open Source, Snyk Code,
# Snyk Container and Snyk Infrastructure as Code)
# The setup installs the Snyk CLI - for more details on the possible commands
# check https://docs.snyk.io/snyk-cli/cli-reference
# The results of Snyk Code are then uploaded to GitHub Security Code Scanning
#
# In order to use the Snyk Action you will need to have a Snyk API token.
# More details in https://github.com/snyk/actions#getting-your-snyk-token
# or you can signup for free at https://snyk.io/login
#
# For more examples, including how to limit scans to only high-severity issues
# and fail PR checks, see https://github.com/snyk/actions/

name: Snyk Security Scan

on:
  push:
    branches: ["Security_branch"]
  pull_request:
    branches: ["Security_branch"]

permissions:
  contents: read

jobs:
  snyk-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install Snyk CLI
        run: npm install -g snyk
      
      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
      
      # List all files to help with debugging
      - name: List files in repository
        run: find . -type f | grep -v ".git" | sort
      
      # Scan using Snyk's Code security scanning
      - name: Run Snyk Code scan
        run: snyk code test
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
      # Monitor using Snyk Code rather than dependency scanning
      - name: Monitor with Snyk Code
        run: snyk code monitor
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
      # Try scanning Java files directly if they exist
      - name: Scan Java files (if any)
        run: |
          java_files=$(find . -name "*.java" -type f)
          if [ -n "$java_files" ]; then
            echo "Found Java files, scanning for vulnerabilities"
            snyk test --scan-all-unmanaged
          else
            echo "No Java files found"
          fi
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
      # Try scanning HTML files directly if they exist
      - name: Scan HTML files (if any)
        run: |
          html_files=$(find . -name "*.html" -type f)
          if [ -n "$html_files" ]; then
            echo "Found HTML files, scanning for vulnerabilities"
            snyk test --scan-all-unmanaged
          else
            echo "No HTML files found"
          fi
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
